<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageId>Salyra.Upload</PackageId>
    <Version>0.1.0</Version>
    <Authors>Salyra UI</Authors>
    <Description>Streaming upload sessions and configurable storage</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://salyra-ui.github.io/docs/upload-server.html</PackageProjectUrl>
    <RepositoryUrl>https://github.com/salyra-ui/file-upload</RepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <None Include="../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
