<?php
namespace Salyra\Upload;
final class DiskStorage implements Storage {
    public function __construct(private string $directory) {}
    private function parts(array $session): string { return $this->directory.'/parts/'.DiskSessions::safe($session['id']); }
    private function result(array $session): string { return $this->directory.'/files/'.DiskSessions::safe($session['id']); }
    private function directory(string $path): void { if (!is_dir($path) && !mkdir($path,0700,true)) throw new \RuntimeException('Could not create directory'); }
    private function remove(string $path): void { if (!is_dir($path)) return; foreach (new \DirectoryIterator($path) as $item) if (!$item->isDot()) { if ($item->isDir()) $this->remove($item->getPathname()); elseif (!unlink($item->getPathname())) throw new \RuntimeException('Could not remove temporary part'); } if (!rmdir($path)) throw new \RuntimeException('Could not remove temporary directory'); }
    public function begin(array $session, mixed $context): mixed { $this->directory($this->parts($session)); return ['version'=>1,'id'=>$session['id']]; }
    public function writePart(array $session, array $part, mixed $body, mixed $context): array {
        $target=$this->parts($session).'/'.$part['index']; if (file_exists($target) && (filesize($target)!==$part['size'] || hash_file('sha256',$target)!==$part['sha256'])) throw new UploadError(409, 'PART_CONFLICT', 'Chunk contains different data');
        $temp=tempnam(dirname($target), '.part-'); if (!$temp) throw new \RuntimeException('Could not create part file');
        try { $output=fopen($temp,'wb'); if (!$output) throw new \RuntimeException('Could not write part'); $hash=hash_init('sha256'); $size=0;
            try { while (!feof($body)) { $data=fread($body,65536); if ($data===false) throw new \RuntimeException('Body read failed'); if ($data==='') break; $size+=strlen($data); if ($size>$part['size']) throw new UploadError(413,'PART_SIZE','Chunk exceeds expected size'); hash_update($hash,$data); $position=0; while ($position<strlen($data)) { $written=fwrite($output,substr($data,$position)); if (!$written) throw new \RuntimeException('Part write failed'); $position+=$written; } } if ($size!==$part['size'] || hash_final($hash)!==$part['sha256']) throw new UploadError(422,'CHECKSUM','Chunk checksum does not match'); fflush($output); fsync($output); } finally { fclose($output); }
            if (!rename($temp,$target)) throw new \RuntimeException('Part publish failed'); $part['reference']=['version'=>1,'index'=>$part['index']]; DiskSessions::atomic($target.'.receipt.json',$part); return $part;
        } finally { if (file_exists($temp)) unlink($temp); }
    }
    public function probe(array $session, mixed $context): array { $parts=[]; $directory=$this->parts($session); if (!is_dir($directory)) return []; foreach (new \DirectoryIterator($directory) as $file) { if (!ctype_digit($file->getFilename())) continue; $path=$file->getPathname(); $receipt=$path.'.receipt.json'; if (file_exists($receipt)) $part=json_decode(file_get_contents($receipt),true,512,JSON_THROW_ON_ERROR); else { $part=['index'=>(int)$file->getFilename(),'size'=>$file->getSize(),'sha256'=>hash_file('sha256',$path),'reference'=>['version'=>1,'index'=>(int)$file->getFilename()]]; DiskSessions::atomic($receipt,$part); } if ($part['size']!==$file->getSize()) throw new UploadError(500,'STORAGE_CHECKPOINT','Stored chunk changed'); $parts[]=$part; } usort($parts,fn($a,$b)=>$a['index']<=>$b['index']); return $parts; }
    public function inspectResult(array $session, mixed $context): mixed { $path=$this->result($session); if (!file_exists($path)) return null; if (filesize($path)!==$session['descriptor']['size']) throw new UploadError(500,'RESULT_SIZE','Completed file size does not match'); return ['id'=>$session['id'],'size'=>filesize($path),'sha256'=>hash_file('sha256',$path)]; }
    public function finish(array $session, array $parts, mixed $context): mixed {
        $result=$this->inspectResult($session,$context); if ($result!==null) return $result; $target=$this->result($session); $this->directory(dirname($target)); $temp=tempnam(dirname($target),'.result-'); if (!$temp) throw new \RuntimeException('Could not create final file');
        try { $out=fopen($temp,'wb'); if (!$out) throw new \RuntimeException('Could not write final file'); $hash=hash_init('sha256'); $total=0;
            try { foreach ($parts as $part) { $path=$this->parts($session).'/'.$part['index']; $stream=fopen($path,'rb'); if (!$stream) throw new \RuntimeException('Saved chunk missing'); $partHash=hash_init('sha256'); $size=0; try { while (!feof($stream)) { $data=fread($stream,65536); if ($data===false) throw new \RuntimeException('Part read failed'); if ($data==='') break; hash_update($hash,$data); hash_update($partHash,$data); $size+=strlen($data); $position=0; while ($position<strlen($data)) { $written=fwrite($out,substr($data,$position)); if (!$written) throw new \RuntimeException('Final file write failed'); $position+=$written; } } } finally { fclose($stream); } if ($size!==$part['size'] || hash_final($partHash)!==$part['sha256']) throw new UploadError(422,'CHECKSUM','Saved chunk changed'); $total+=$size; } if ($total!==$session['descriptor']['size']) throw new UploadError(422,'SIZE','Assembled size does not match'); fflush($out); fsync($out); } finally { fclose($out); }
            if (!rename($temp,$target)) throw new \RuntimeException('Final file publish failed'); $this->remove($this->parts($session)); return ['id'=>$session['id'],'size'=>$total,'sha256'=>hash_final($hash)];
        } finally { if (file_exists($temp)) unlink($temp); }
    }
    public function abort(array $session, mixed $context): void { $this->remove($this->parts($session)); }
}
